services:
  mjakazi-connect-mock:
    image: ghcr.io/m6o4solutions/mjakazi-connect-mock:latest
    container_name: mjakazi-connect-mock
    restart: unless-stopped
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mjakazi-connect-mock.rule=Host(`mock.mjakaziconnect.co.ke`)"
      - "traefik.http.routers.mjakazi-connect-mock.entrypoints=websecure"
      - "traefik.http.routers.mjakazi-connect-mock.tls.certresolver=letsencrypt"
      - "traefik.http.services.mjakazi-connect-mock.loadbalancer.server.port=80"

networks:
  traefik-network:
    external: true
    name: traefik-network
